### ISSUE TITLE
Fix the compilation of `log2` method in tutorials

### ISSUE THREAD

**Issue by mstechly** [PsiQ/bartiq#32]
There is some issue in the compilation in the basic tutorial which results in an uncompiled value at the end of the evaluation: `log2(120)`. 

Needs to be investigated, might be related to https://github.com/PsiQ/bartiq/issues/25.

**Comment by bdg221** [comment]
This behavior is the result of sympy trying to be helpful. When the result is not "clean" (I haven't found the exact details, but it appears to be when it is not an integer), then sympy returns the expression written out. 

![image](https://github.com/PsiQ/bartiq/assets/62308289/74e1757e-d412-4514-b6f1-06c9e423b07e)

![image](https://github.com/PsiQ/bartiq/assets/62308289/e7954ba7-1459-4e12-a98f-5656d01000c0)

![image](https://github.com/PsiQ/bartiq/assets/62308289/abcc55dd-a631-4ea0-beb4-ac6ace33493c)

This can be verified by simply changing the  to use L=32 in the alias sampling tutorial (not the basic tutorial):
![image](https://github.com/PsiQ/bartiq/assets/62308289/b7ac40ce-07d3-4d20-8e1d-95cb06e6818e)

As can be seen, evalf() returned a float. Currently, in `sympy_interpreter.py` the `create_function` function in the `SympyInterpreter` class pulls the function from SPECIAL_FUNCS and eventually returns `func(*args)`. At first glance, I cannot think of an easy way to include the evalf(), especially since not all of the functions in SPECIAL_FUNCS come from sympy (ie. abs, Round...)

**Comment by mstechly** [comment]
Oh, interesting!
I see how having that makes sense – this way the expressions are exact and we don't lose precision. I think this means it's actually a feature and not a bug 🎉 

Thanks a lot for tracking this down Brian – I think we now need to decide what we want to do about it.

I think we could add a flag to `evaluate` that will force calling `evalf` (or sth similar) on the final expression if True. And I'd expect it to be True by default.

Looking at how these things are being called, it looks like a lot of flag passing to me though.
@dexter2206, any better ideas?

**Comment by mstechly** [comment]
FYI @bdg221 , here's how we fixed it: https://github.com/PsiQ/bartiq/pull/52
It turns out that `DependentVariable` already had the value evaluated, but we were returning an expression instead.
It now always returns numerical value :)
