### ISSUE TITLE
Bartiq gets installed with version 0.0.0

### ISSUE THREAD

**Issue by mstechly** [PsiQ/bartiq#41]
When installing bartiq in a fresh venv with `poetry install` it gets installed with the version `0.0.0` (the last message from the install log I get is `Installing the current project: bartiq (0.0.0)`. 

This is most likely due to the setup with dynamic versioning and the fact that `0.0.0` is set as a default version.

CC: @dexter2206

**Comment by bdg221** [comment]
@mstechly @dexter2206 
The poetry-dynamic-versioning needs to be installed with the "plugin" feature to correct the behavior that is currently seen. 

Here are a few issues that they have related to this. (Usually, it is seen during CI worklfow.)
https://github.com/mtkennerly/poetry-dynamic-versioning/issues/174
https://github.com/mtkennerly/poetry-dynamic-versioning/issues/145
https://github.com/mtkennerly/poetry-dynamic-versioning/issues/126

On my system, I started from a clean environment and followed the Bartiq [development instructions](https://psiq.github.io/bartiq/latest/installation/#development). However, I did the following:
```
git clone git@github.com:PsiQ/bartiq.git
cd bartiq
pip install poetry "poetry-dynamic-versioning[plugin]"
poetry install
```

After install the plugin feature, `poetry install` now shows `Installing the current project: bartiq (0.1.2.post4.dev0+49b1f69)`.

Checking the [poetry documentation on plugs](https://python-poetry.org/docs/plugins/#using-plugins), it looks like `pipx`, `pip`, or `poetry self add` can be used. However, since the documentation already includes `pip`, it makes sense to stick with it.

I wanted to double check that the pattern of the version is acceptable before creating a PR for the documentation change.

**Comment by mstechly** [comment]
What you proposed sounds good, thanks for looking into it!

**Comment by mstechly** [comment]
As it turns out, it got fixed by changes in the release mechanism and currently works properly without the proposed change, closing the issue.
