### ISSUE TITLE
Passthrough port sizes don't get compiled correctly

### ISSUE THREAD

**Issue by mstechly** [PsiQ/bartiq#72]
After running the following piece of code:

```
import json
from bartiq import Routine, compile_routine, evaluate
from bartiq.integrations import qref_to_bartiq

with open("docs/data/alias_sampling_basic.json", "r") as f:
    routine_dict = json.load(f)

uncompiled_routine = qref_to_bartiq(routine_dict)
compiled_routine = compile_routine(uncompiled_routine)
```
And inspecting `swap`:
```
compiled_routine.children["swap"]
```
I get the following result:
<img width="375" alt="Screenshot 2024-06-19 at 7 26 01 PM" src="https://github.com/PsiQ/bartiq/assets/7314136/1da03744-5a79-4c5f-b6ce-8e0c9a0b23eb">

These `P_1` and `P_2` are not defined anywhere, they are placeholder variables coming from the passthroughs. At this stage they should have been replaced by real values coming from ports they're connected to, but something went wrong.

This might get resolved while working on #18 , but if not, needs to be fixed after it's resolved.

I was using `bartiq==0.2.0`.

**Comment by mstechly** [comment]
A potentially related issue:

When running basic tutorial as part of https://github.com/PsiQ/bartiq/pull/76 with new verification, I got the following message:
`/Users/mstechly/Documents/code/2024-06-04-18-validation/bartiq/src/bartiq/compilation/_compile.py:117: UserWarning: Found the following issues with the provided routine after the compilation has finished: ["Symbol n_b found in subroutine: my_algorithm.B, which is not among top level params: {'n', 'z'}."]`

Here similarly, the `n_b` does not get compiled out – it might be the same or related bug.

**Comment by sitong1011** [comment]
Although I created the `parse_constant` function to replace mathematical constants like pi in an expression and ignore case sensitivity after using `as_expression`, I found that simply using` sympify `avoids this issue as `sympify` automatically converts mathematical constants in `sympy` to their correct constant values rather than `Symbol` type. 

Interestingly, `as_expression `also uses the same sympify function. I suspect this discrepancy might be related to the output type of `as_expression`.
```
sympify('pi'): <class 'sympy.core.numbers.Pi'> pi
sympy_backend.as_expression('pi'):<class 'sympy.core.symbol.Symbol'>
```
@mstechly @dexter2206
